### ISSUE TITLE
draw crs error

### ISSUE THREAD

**Issue by lfelker** [AccessMap/sidewalkify#1]
draw() now takes a crs as a parameter, but the crs format of the default (crs = 4326) should really be crs = {'init': 'epsg:4326'} if the crs is set by saying gdf.crs = crs. The error occurs because gdf.crs = 4326 is not a valid format.

**Comment by nbolten** [comment]
I think this is fixed! Let me know if it's still broken.

**Comment by lfelker** [comment]
yeah this is good now!
